# dataSource
spring:
  # redis配置(非集群)
  redis:
    host: 127.0.0.1
    port: 6379
    pool:
      # 连接池中的最大空闲连接 
      max-idle: 20
      # 连接池中的最小空闲连接 
      min-idle: 10
      # 连接池最大连接数（使用负值表示没有限制） 
      max-active: 100
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: 3000